name: rpf
base: core22
version: '1.0.0'
summary: A modular radio player built with Flutter
description: |
  Radio Player (Flutter) is a lightweight, bilingual radio player built with Flutter. It streams Swiss stations and logs playback events with Firebase Analytics.

grade: stable
confinement: strict

apps:
  rpf:
    command: bin/rpf
    extensions: [gnome]
    plugs:
      - network
      - audio-playback
      - desktop
      - desktop-legacy
      - x11
      - wayland

parts:
  rpf:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
    build-packages:
      - libgtk-3-dev
      - libglib2.0-dev
      - libstdc++-12-dev
    stage-packages:
      - libgtk-3-0
      - libglib2.0-0
      - libstdc++6
