// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUTcxWiRmiRt_pFDGWorU9LrB3WUaqy3A',
    appId: '1:291517706187:web:06c79de6973d28301ed04e',
    messagingSenderId: '291517706187',
    projectId: 'android-apps-6285e',
    authDomain: 'android-apps-6285e.firebaseapp.com',
    storageBucket: 'android-apps-6285e.firebasestorage.app',
    measurementId: 'G-RZWDBY3C63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoxJSOl2Y4VZlL0m_1XWpI9VQl7BQLOzE',
    appId: '1:291517706187:android:2d62f24e29d13f181ed04e',
    messagingSenderId: '291517706187',
    projectId: 'android-apps-6285e',
    storageBucket: 'android-apps-6285e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUTcxWiRmiRt_pFDGWorU9LrB3WUaqy3A',
    appId: '1:291517706187:web:c5365fc726f663a31ed04e',
    messagingSenderId: '291517706187',
    projectId: 'android-apps-6285e',
    authDomain: 'android-apps-6285e.firebaseapp.com',
    storageBucket: 'android-apps-6285e.firebasestorage.app',
    measurementId: 'G-GPH2YQM6CZ',
  );
}
